### ISSUE TITLE
build for node 12

### ISSUE THREAD

**Issue by galkahana** [cscott/node-icu-bidi#4]
Hi,
Build ain't working with node 12, which makes sense as the v8 engine got replaced.
i'm gonna have a go at adaptation, if you got anything ready, please share.

b.t.w thanks a lot for this, been working wonderfully so far.

Thanks,
Gal.

**Comment by cscott** [comment]
Fixed in 0.1.4.

**Comment by galkahana** [comment]
thanks man!
