### ISSUE TITLE
Bug occured when installing on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Stieltjes** [cscott/node-icu-bidi#8]
[npm-debug-log.docx](https://github.com/cscott/node-icu-bidi/files/314597/npm-debug-log.docx)

Bug occured when installing icu-bidi on Ubuntu 16.04 LTS, basically I got the error saying

node-pre-gyp ERR! Tried to download: https://github.com/cscott/node-icu-bidi/releases/download/0.1.5-git/icu_bidi-v0.1.5-git-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for icu-bidi@0.1.5-git and node@6.2.1 (node-v48 ABI) (falling back to source compile with node-gyp)

**Comment by cscott** [comment]
Dup of PR #7.
